services:
  - type: web
    name: MonAppPHP
    env: docker
    plan: free
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: DB_HOST
        value: <localhost>
      - key: DB_NAME
        value: <db>
      - key: DB_USER
        value: <postgres>
      - key: DB_PASSWORD
        value: <postgis>
      - key: DB_PORT
        value: "5432"
